// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  familyId: __t.string().name("family_id"),
  patient: __t.string(),
  patientName: __t.string().name("patient_name"),
  organizer: __t.string(),
  organizerName: __t.string().name("organizer_name"),
  slot: __t.string(),
  status: __t.string(),
  created: __t.u64(),
});
