// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.10.2 (commit 58d2a40718c59535fd5c267e836d473298eb84d5).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import CancelDemoBookingReducer from "./cancel_demo_booking_reducer";
import CancelFamilyVisitReducer from "./cancel_family_visit_reducer";
import CancelTaskReducer from "./cancel_task_reducer";
import CancelTripReducer from "./cancel_trip_reducer";
import CheckRemindersReducer from "./check_reminders_reducer";
import ClaimTaskReducer from "./claim_task_reducer";
import CompletePlanStepReducer from "./complete_plan_step_reducer";
import CompleteTaskReducer from "./complete_task_reducer";
import ConfirmAiTaskReducer from "./confirm_ai_task_reducer";
import ConfirmDemoBookingReducer from "./confirm_demo_booking_reducer";
import ConfirmFamilyVisitReducer from "./confirm_family_visit_reducer";
import CreateFamilyReducer from "./create_family_reducer";
import CreateInviteReducer from "./create_invite_reducer";
import CreateReminderReducer from "./create_reminder_reducer";
import CreateTaskReducer from "./create_task_reducer";
import DeclineTaskReducer from "./decline_task_reducer";
import DismissCareReducer from "./dismiss_care_reducer";
import JoinFamilyReducer from "./join_family_reducer";
import PostFamilyMessageReducer from "./post_family_message_reducer";
import PublishEmergencyCardReducer from "./publish_emergency_card_reducer";
import RemindPlanStepReducer from "./remind_plan_step_reducer";
import ReviewCareReducer from "./review_care_reducer";
import RevokeMemberReducer from "./revoke_member_reducer";
import SaveTripReducer from "./save_trip_reducer";
import SendMessageReducer from "./send_message_reducer";
import SetAutoCareReducer from "./set_auto_care_reducer";
import SetSharingPreferenceReducer from "./set_sharing_preference_reducer";
import ShareCareBriefReducer from "./share_care_brief_reducer";
import ShareLatestSummaryReducer from "./share_latest_summary_reducer";
import SharePlanStepReducer from "./share_plan_step_reducer";
import SharePreparedVisitReducer from "./share_prepared_visit_reducer";
import ShareSummaryReducer from "./share_summary_reducer";
import UnpublishEmergencyCardReducer from "./unpublish_emergency_card_reducer";
import UpdatePlanReducer from "./update_plan_reducer";
import UpdateReminderReducer from "./update_reminder_reducer";

// Import all procedure arg schemas
import * as BeginSandboxProcedure from "./begin_sandbox_procedure";
import * as FinishAiProcedure from "./finish_ai_procedure";
import * as FinishCareProcedure from "./finish_care_procedure";
import * as FinishPlanProcedure from "./finish_plan_procedure";
import * as FinishSandboxProcedure from "./finish_sandbox_procedure";
import * as PrepareAiProcedure from "./prepare_ai_procedure";
import * as PrepareCareProcedure from "./prepare_care_procedure";
import * as PreparePlanProcedure from "./prepare_plan_procedure";
import * as RefreshRecordsProcedure from "./refresh_records_procedure";

// Import all table schema definitions
import FamilyEmergencyCardsRow from "./family_emergency_cards_table";
import FamilyMembersRow from "./family_members_table";
import FamilyTasksRow from "./family_tasks_table";
import FamilyVisitsRow from "./family_visits_table";
import MyAutoCarePreferenceRow from "./my_auto_care_preference_table";
import MyBookingsRow from "./my_bookings_table";
import MyCarePlansRow from "./my_care_plans_table";
import MyCarePreparationRow from "./my_care_preparation_table";
import MyInvitesRow from "./my_invites_table";
import MyMembershipRow from "./my_membership_table";
import MyRecordConnectionRow from "./my_record_connection_table";
import MyRecordsRow from "./my_records_table";
import MyRemindersRow from "./my_reminders_table";
import MySandboxLinkRow from "./my_sandbox_link_table";
import MySharingPreferenceRow from "./my_sharing_preference_table";
import VisibleMessagesRow from "./visible_messages_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  familyEmergencyCards: __table({
    name: 'family_emergency_cards',
    indexes: [
    ],
    constraints: [
    ],
  }, FamilyEmergencyCardsRow),
  familyMembers: __table({
    name: 'family_members',
    indexes: [
    ],
    constraints: [
    ],
  }, FamilyMembersRow),
  familyTasks: __table({
    name: 'family_tasks',
    indexes: [
    ],
    constraints: [
    ],
  }, FamilyTasksRow),
  familyVisits: __table({
    name: 'family_visits',
    indexes: [
    ],
    constraints: [
    ],
  }, FamilyVisitsRow),
  myAutoCarePreference: __table({
    name: 'my_auto_care_preference',
    indexes: [
    ],
    constraints: [
    ],
  }, MyAutoCarePreferenceRow),
  myBookings: __table({
    name: 'my_bookings',
    indexes: [
    ],
    constraints: [
    ],
  }, MyBookingsRow),
  myCarePlans: __table({
    name: 'my_care_plans',
    indexes: [
    ],
    constraints: [
    ],
  }, MyCarePlansRow),
  myCarePreparation: __table({
    name: 'my_care_preparation',
    indexes: [
    ],
    constraints: [
    ],
  }, MyCarePreparationRow),
  myInvites: __table({
    name: 'my_invites',
    indexes: [
    ],
    constraints: [
    ],
  }, MyInvitesRow),
  myMembership: __table({
    name: 'my_membership',
    indexes: [
    ],
    constraints: [
    ],
  }, MyMembershipRow),
  myRecordConnection: __table({
    name: 'my_record_connection',
    indexes: [
    ],
    constraints: [
    ],
  }, MyRecordConnectionRow),
  myRecords: __table({
    name: 'my_records',
    indexes: [
    ],
    constraints: [
    ],
  }, MyRecordsRow),
  myReminders: __table({
    name: 'my_reminders',
    indexes: [
    ],
    constraints: [
    ],
  }, MyRemindersRow),
  mySandboxLink: __table({
    name: 'my_sandbox_link',
    indexes: [
    ],
    constraints: [
    ],
  }, MySandboxLinkRow),
  mySharingPreference: __table({
    name: 'my_sharing_preference',
    indexes: [
    ],
    constraints: [
    ],
  }, MySharingPreferenceRow),
  visibleMessages: __table({
    name: 'visible_messages',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleMessagesRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("cancel_demo_booking", CancelDemoBookingReducer),
  __reducerSchema("cancel_family_visit", CancelFamilyVisitReducer),
  __reducerSchema("cancel_task", CancelTaskReducer),
  __reducerSchema("cancel_trip", CancelTripReducer),
  __reducerSchema("check_reminders", CheckRemindersReducer),
  __reducerSchema("claim_task", ClaimTaskReducer),
  __reducerSchema("complete_plan_step", CompletePlanStepReducer),
  __reducerSchema("complete_task", CompleteTaskReducer),
  __reducerSchema("confirm_ai_task", ConfirmAiTaskReducer),
  __reducerSchema("confirm_demo_booking", ConfirmDemoBookingReducer),
  __reducerSchema("confirm_family_visit", ConfirmFamilyVisitReducer),
  __reducerSchema("create_family", CreateFamilyReducer),
  __reducerSchema("create_invite", CreateInviteReducer),
  __reducerSchema("create_reminder", CreateReminderReducer),
  __reducerSchema("create_task", CreateTaskReducer),
  __reducerSchema("decline_task", DeclineTaskReducer),
  __reducerSchema("dismiss_care", DismissCareReducer),
  __reducerSchema("join_family", JoinFamilyReducer),
  __reducerSchema("post_family_message", PostFamilyMessageReducer),
  __reducerSchema("publish_emergency_card", PublishEmergencyCardReducer),
  __reducerSchema("remind_plan_step", RemindPlanStepReducer),
  __reducerSchema("review_care", ReviewCareReducer),
  __reducerSchema("revoke_member", RevokeMemberReducer),
  __reducerSchema("save_trip", SaveTripReducer),
  __reducerSchema("send_message", SendMessageReducer),
  __reducerSchema("set_auto_care", SetAutoCareReducer),
  __reducerSchema("set_sharing_preference", SetSharingPreferenceReducer),
  __reducerSchema("share_care_brief", ShareCareBriefReducer),
  __reducerSchema("share_latest_summary", ShareLatestSummaryReducer),
  __reducerSchema("share_plan_step", SharePlanStepReducer),
  __reducerSchema("share_prepared_visit", SharePreparedVisitReducer),
  __reducerSchema("share_summary", ShareSummaryReducer),
  __reducerSchema("unpublish_emergency_card", UnpublishEmergencyCardReducer),
  __reducerSchema("update_plan", UpdatePlanReducer),
  __reducerSchema("update_reminder", UpdateReminderReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
  __procedureSchema("begin_sandbox", BeginSandboxProcedure.params, BeginSandboxProcedure.returnType),
  __procedureSchema("finish_ai", FinishAiProcedure.params, FinishAiProcedure.returnType),
  __procedureSchema("finish_care", FinishCareProcedure.params, FinishCareProcedure.returnType),
  __procedureSchema("finish_plan", FinishPlanProcedure.params, FinishPlanProcedure.returnType),
  __procedureSchema("finish_sandbox", FinishSandboxProcedure.params, FinishSandboxProcedure.returnType),
  __procedureSchema("prepare_ai", PrepareAiProcedure.params, PrepareAiProcedure.returnType),
  __procedureSchema("prepare_care", PrepareCareProcedure.params, PrepareCareProcedure.returnType),
  __procedureSchema("prepare_plan", PreparePlanProcedure.params, PreparePlanProcedure.returnType),
  __procedureSchema("refresh_records", RefreshRecordsProcedure.params, RefreshRecordsProcedure.returnType),
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.10.2" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The procedures available in this remote SpacetimeDB module. */
export const procedures = __convertToAccessorMap(proceduresSchema.procedures);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

