// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  owner: __t.string(),
  familyId: __t.string().name("family_id"),
  kind: __t.string(),
  status: __t.string(),
  summary: __t.string(),
  plan: __t.string(),
  evidence: __t.string(),
  revision: __t.u64(),
  started: __t.u64(),
  generatedAt: __t.u64().name("generated_at"),
  reviewedAt: __t.u64().name("reviewed_at"),
  dismissedAt: __t.u64().name("dismissed_at"),
  completed: __t.array(__t.string()),
  shared: __t.array(__t.string()),
  handledAt: __t.u64().name("handled_at"),
  completedAt: __t.string().name("completed_at"),
});
