// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  owner: __t.string().primaryKey(),
  familyId: __t.string().name("family_id"),
  appointmentId: __t.string().name("appointment_id"),
  appointmentDate: __t.string().name("appointment_date"),
  status: __t.string(),
  dismissed: __t.bool(),
  text: __t.string(),
  evidence: __t.string(),
  warnings: __t.array(__t.string()),
  revision: __t.u64(),
  generation: __t.u64(),
  started: __t.u64(),
  sharedMessage: __t.option(__t.u64()).name("shared_message"),
  taskId: __t.option(__t.string()).name("task_id"),
  generatedAt: __t.u64().name("generated_at"),
  reviewedAt: __t.u64().name("reviewed_at"),
  dismissedAt: __t.u64().name("dismissed_at"),
  handledAt: __t.u64().name("handled_at"),
});
