// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  owner: __t.string().primaryKey(),
  scenario: __t.string(),
  subject: __t.string(),
  displayName: __t.string().name("display_name"),
  status: __t.string(),
  retrievedAt: __t.string().name("retrieved_at"),
  warnings: __t.array(__t.string()),
  details: __t.string(),
  revision: __t.u64(),
});
