// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  owner: __t.string().primaryKey(),
  familyId: __t.string().name("family_id"),
  requestId: __t.string().name("request_id"),
  scenario: __t.string(),
  sessionId: __t.string().name("session_id"),
  subject: __t.string(),
  status: __t.string(),
  revision: __t.u64(),
  started: __t.u64(),
});
