// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AiJob = __t.object("AiJob", {
  id: __t.string(),
  owner: __t.string(),
  familyId: __t.string(),
  audience: __t.string(),
  question: __t.string(),
  status: __t.string(),
  evidence: __t.string(),
  revision: __t.u64(),
  created: __t.u64(),
  history: __t.string(),
});
export type AiJob = __Infer<typeof AiJob>;

export const Audit = __t.object("Audit", {
  id: __t.u64(),
  familyId: __t.string(),
  actor: __t.string(),
  action: __t.string(),
  created: __t.u64(),
});
export type Audit = __Infer<typeof Audit>;

export const AutoCarePreference = __t.object("AutoCarePreference", {
  owner: __t.string(),
  enabled: __t.bool(),
});
export type AutoCarePreference = __Infer<typeof AutoCarePreference>;

export const Booking = __t.object("Booking", {
  id: __t.string(),
  owner: __t.string(),
  slot: __t.string(),
  status: __t.string(),
  created: __t.u64(),
});
export type Booking = __Infer<typeof Booking>;

export const CarePlan = __t.object("CarePlan", {
  id: __t.string(),
  owner: __t.string(),
  familyId: __t.string(),
  kind: __t.string(),
  status: __t.string(),
  summary: __t.string(),
  plan: __t.string(),
  evidence: __t.string(),
  revision: __t.u64(),
  started: __t.u64(),
  generatedAt: __t.u64(),
  reviewedAt: __t.u64(),
  dismissedAt: __t.u64(),
  completed: __t.array(__t.string()),
  shared: __t.array(__t.string()),
  handledAt: __t.u64(),
  completedAt: __t.string(),
});
export type CarePlan = __Infer<typeof CarePlan>;

export const CarePreparation = __t.object("CarePreparation", {
  owner: __t.string(),
  familyId: __t.string(),
  appointmentId: __t.string(),
  appointmentDate: __t.string(),
  status: __t.string(),
  dismissed: __t.bool(),
  text: __t.string(),
  evidence: __t.string(),
  warnings: __t.array(__t.string()),
  revision: __t.u64(),
  generation: __t.u64(),
  started: __t.u64(),
  sharedMessage: __t.option(__t.u64()),
  taskId: __t.option(__t.string()),
  generatedAt: __t.u64(),
  reviewedAt: __t.u64(),
  dismissedAt: __t.u64(),
  handledAt: __t.u64(),
});
export type CarePreparation = __Infer<typeof CarePreparation>;

export const EmergencyCard = __t.object("EmergencyCard", {
  owner: __t.string(),
  familyId: __t.string(),
  name: __t.string(),
  data: __t.string(),
  reviewedAt: __t.u64(),
});
export type EmergencyCard = __Infer<typeof EmergencyCard>;

export const FamilyEmergencyCards = __t.object("FamilyEmergencyCards", {});
export type FamilyEmergencyCards = __Infer<typeof FamilyEmergencyCards>;

export const FamilyMembers = __t.object("FamilyMembers", {});
export type FamilyMembers = __Infer<typeof FamilyMembers>;

export const FamilyTasks = __t.object("FamilyTasks", {});
export type FamilyTasks = __Infer<typeof FamilyTasks>;

export const FamilyVisit = __t.object("FamilyVisit", {
  id: __t.string(),
  familyId: __t.string(),
  patient: __t.string(),
  patientName: __t.string(),
  organizer: __t.string(),
  organizerName: __t.string(),
  slot: __t.string(),
  status: __t.string(),
  created: __t.u64(),
});
export type FamilyVisit = __Infer<typeof FamilyVisit>;

export const FamilyVisits = __t.object("FamilyVisits", {});
export type FamilyVisits = __Infer<typeof FamilyVisits>;

export const Invite = __t.object("Invite", {
  code: __t.string(),
  familyId: __t.string(),
  issuer: __t.string(),
  name: __t.string(),
  expires: __t.u64(),
  used: __t.bool(),
});
export type Invite = __Infer<typeof Invite>;

export const Membership = __t.object("Membership", {
  identity: __t.string(),
  familyId: __t.string(),
  name: __t.string(),
  role: __t.string(),
});
export type Membership = __Infer<typeof Membership>;

export const Message = __t.object("Message", {
  id: __t.u64(),
  familyId: __t.string(),
  owner: __t.string(),
  audience: __t.string(),
  author: __t.string(),
  text: __t.string(),
  sourceIds: __t.array(__t.string()),
  shared: __t.bool(),
  created: __t.u64(),
  mode: __t.string(),
  evidence: __t.option(__t.string()),
  proposal: __t.option(__t.string()),
});
export type Message = __Infer<typeof Message>;

export const MyAutoCarePreference = __t.object("MyAutoCarePreference", {});
export type MyAutoCarePreference = __Infer<typeof MyAutoCarePreference>;

export const MyBookings = __t.object("MyBookings", {});
export type MyBookings = __Infer<typeof MyBookings>;

export const MyCarePlans = __t.object("MyCarePlans", {});
export type MyCarePlans = __Infer<typeof MyCarePlans>;

export const MyCarePreparation = __t.object("MyCarePreparation", {});
export type MyCarePreparation = __Infer<typeof MyCarePreparation>;

export const MyInvites = __t.object("MyInvites", {});
export type MyInvites = __Infer<typeof MyInvites>;

export const MyMembership = __t.object("MyMembership", {});
export type MyMembership = __Infer<typeof MyMembership>;

export const MyRecordConnection = __t.object("MyRecordConnection", {});
export type MyRecordConnection = __Infer<typeof MyRecordConnection>;

export const MyRecords = __t.object("MyRecords", {});
export type MyRecords = __Infer<typeof MyRecords>;

export const MyReminders = __t.object("MyReminders", {});
export type MyReminders = __Infer<typeof MyReminders>;

export const MySandboxLink = __t.object("MySandboxLink", {});
export type MySandboxLink = __Infer<typeof MySandboxLink>;

export const MySharingPreference = __t.object("MySharingPreference", {});
export type MySharingPreference = __Infer<typeof MySharingPreference>;

export const Record = __t.object("Record", {
  id: __t.string(),
  owner: __t.string(),
  person: __t.string(),
  category: __t.string(),
  text: __t.string(),
  date: __t.option(__t.string()),
  provenance: __t.option(__t.string()),
});
export type Record = __Infer<typeof Record>;

export const RecordConnection = __t.object("RecordConnection", {
  owner: __t.string(),
  scenario: __t.string(),
  subject: __t.string(),
  displayName: __t.string(),
  status: __t.string(),
  retrievedAt: __t.string(),
  warnings: __t.array(__t.string()),
  details: __t.string(),
  revision: __t.u64(),
});
export type RecordConnection = __Infer<typeof RecordConnection>;

export const Reminder = __t.object("Reminder", {
  id: __t.string(),
  owner: __t.string(),
  title: __t.string(),
  dueAt: __t.u64(),
  status: __t.string(),
  created: __t.u64(),
});
export type Reminder = __Infer<typeof Reminder>;

export const Request = __t.object("Request", {
  id: __t.string(),
  caller: __t.string(),
  operation: __t.string(),
  payload: __t.string(),
});
export type Request = __Infer<typeof Request>;

export const SandboxLink = __t.object("SandboxLink", {
  owner: __t.string(),
  familyId: __t.string(),
  requestId: __t.string(),
  scenario: __t.string(),
  sessionId: __t.string(),
  subject: __t.string(),
  status: __t.string(),
  revision: __t.u64(),
  started: __t.u64(),
});
export type SandboxLink = __Infer<typeof SandboxLink>;

export const SharingPreference = __t.object("SharingPreference", {
  owner: __t.string(),
  familyId: __t.string(),
  mode: __t.string(),
});
export type SharingPreference = __Infer<typeof SharingPreference>;

export const Task = __t.object("Task", {
  id: __t.string(),
  familyId: __t.string(),
  title: __t.string(),
  owner: __t.string(),
  ownerName: __t.string(),
  status: __t.string(),
  creator: __t.string(),
  declined: __t.array(__t.string()),
  created: __t.u64(),
  updated: __t.u64(),
});
export type Task = __Infer<typeof Task>;

export const VisibleMessages = __t.object("VisibleMessages", {});
export type VisibleMessages = __Infer<typeof VisibleMessages>;

