// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  familyId: __t.string().name("family_id"),
  owner: __t.string(),
  audience: __t.string(),
  author: __t.string(),
  text: __t.string(),
  sourceIds: __t.array(__t.string()).name("source_ids"),
  shared: __t.bool(),
  created: __t.u64(),
  mode: __t.string(),
  evidence: __t.option(__t.string()),
  proposal: __t.option(__t.string()),
});
