// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all procedure arg schemas
import * as BeginSandboxProcedure from "../begin_sandbox_procedure";
import * as FinishAiProcedure from "../finish_ai_procedure";
import * as FinishCareProcedure from "../finish_care_procedure";
import * as FinishPlanProcedure from "../finish_plan_procedure";
import * as FinishSandboxProcedure from "../finish_sandbox_procedure";
import * as PrepareAiProcedure from "../prepare_ai_procedure";
import * as PrepareCareProcedure from "../prepare_care_procedure";
import * as PreparePlanProcedure from "../prepare_plan_procedure";
import * as RefreshRecordsProcedure from "../refresh_records_procedure";

export type BeginSandboxArgs = __Infer<typeof BeginSandboxProcedure.params>;
export type BeginSandboxResult = __Infer<typeof BeginSandboxProcedure.returnType>;
export type FinishAiArgs = __Infer<typeof FinishAiProcedure.params>;
export type FinishAiResult = __Infer<typeof FinishAiProcedure.returnType>;
export type FinishCareArgs = __Infer<typeof FinishCareProcedure.params>;
export type FinishCareResult = __Infer<typeof FinishCareProcedure.returnType>;
export type FinishPlanArgs = __Infer<typeof FinishPlanProcedure.params>;
export type FinishPlanResult = __Infer<typeof FinishPlanProcedure.returnType>;
export type FinishSandboxArgs = __Infer<typeof FinishSandboxProcedure.params>;
export type FinishSandboxResult = __Infer<typeof FinishSandboxProcedure.returnType>;
export type PrepareAiArgs = __Infer<typeof PrepareAiProcedure.params>;
export type PrepareAiResult = __Infer<typeof PrepareAiProcedure.returnType>;
export type PrepareCareArgs = __Infer<typeof PrepareCareProcedure.params>;
export type PrepareCareResult = __Infer<typeof PrepareCareProcedure.returnType>;
export type PreparePlanArgs = __Infer<typeof PreparePlanProcedure.params>;
export type PreparePlanResult = __Infer<typeof PreparePlanProcedure.returnType>;
export type RefreshRecordsArgs = __Infer<typeof RefreshRecordsProcedure.params>;
export type RefreshRecordsResult = __Infer<typeof RefreshRecordsProcedure.returnType>;

