// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import CancelDemoBookingReducer from "../cancel_demo_booking_reducer";
import CancelFamilyVisitReducer from "../cancel_family_visit_reducer";
import CancelTaskReducer from "../cancel_task_reducer";
import CancelTripReducer from "../cancel_trip_reducer";
import CheckRemindersReducer from "../check_reminders_reducer";
import ClaimTaskReducer from "../claim_task_reducer";
import CompletePlanStepReducer from "../complete_plan_step_reducer";
import CompleteTaskReducer from "../complete_task_reducer";
import ConfirmAiTaskReducer from "../confirm_ai_task_reducer";
import ConfirmDemoBookingReducer from "../confirm_demo_booking_reducer";
import ConfirmFamilyVisitReducer from "../confirm_family_visit_reducer";
import CreateFamilyReducer from "../create_family_reducer";
import CreateInviteReducer from "../create_invite_reducer";
import CreateReminderReducer from "../create_reminder_reducer";
import CreateTaskReducer from "../create_task_reducer";
import DeclineTaskReducer from "../decline_task_reducer";
import DismissCareReducer from "../dismiss_care_reducer";
import JoinFamilyReducer from "../join_family_reducer";
import PostFamilyMessageReducer from "../post_family_message_reducer";
import PublishEmergencyCardReducer from "../publish_emergency_card_reducer";
import RemindPlanStepReducer from "../remind_plan_step_reducer";
import ReviewCareReducer from "../review_care_reducer";
import RevokeMemberReducer from "../revoke_member_reducer";
import SaveTripReducer from "../save_trip_reducer";
import SendMessageReducer from "../send_message_reducer";
import SetAutoCareReducer from "../set_auto_care_reducer";
import SetSharingPreferenceReducer from "../set_sharing_preference_reducer";
import ShareCareBriefReducer from "../share_care_brief_reducer";
import ShareLatestSummaryReducer from "../share_latest_summary_reducer";
import SharePlanStepReducer from "../share_plan_step_reducer";
import SharePreparedVisitReducer from "../share_prepared_visit_reducer";
import ShareSummaryReducer from "../share_summary_reducer";
import UnpublishEmergencyCardReducer from "../unpublish_emergency_card_reducer";
import UpdatePlanReducer from "../update_plan_reducer";
import UpdateReminderReducer from "../update_reminder_reducer";

export type CancelDemoBookingParams = __Infer<typeof CancelDemoBookingReducer>;
export type CancelFamilyVisitParams = __Infer<typeof CancelFamilyVisitReducer>;
export type CancelTaskParams = __Infer<typeof CancelTaskReducer>;
export type CancelTripParams = __Infer<typeof CancelTripReducer>;
export type CheckRemindersParams = __Infer<typeof CheckRemindersReducer>;
export type ClaimTaskParams = __Infer<typeof ClaimTaskReducer>;
export type CompletePlanStepParams = __Infer<typeof CompletePlanStepReducer>;
export type CompleteTaskParams = __Infer<typeof CompleteTaskReducer>;
export type ConfirmAiTaskParams = __Infer<typeof ConfirmAiTaskReducer>;
export type ConfirmDemoBookingParams = __Infer<typeof ConfirmDemoBookingReducer>;
export type ConfirmFamilyVisitParams = __Infer<typeof ConfirmFamilyVisitReducer>;
export type CreateFamilyParams = __Infer<typeof CreateFamilyReducer>;
export type CreateInviteParams = __Infer<typeof CreateInviteReducer>;
export type CreateReminderParams = __Infer<typeof CreateReminderReducer>;
export type CreateTaskParams = __Infer<typeof CreateTaskReducer>;
export type DeclineTaskParams = __Infer<typeof DeclineTaskReducer>;
export type DismissCareParams = __Infer<typeof DismissCareReducer>;
export type JoinFamilyParams = __Infer<typeof JoinFamilyReducer>;
export type PostFamilyMessageParams = __Infer<typeof PostFamilyMessageReducer>;
export type PublishEmergencyCardParams = __Infer<typeof PublishEmergencyCardReducer>;
export type RemindPlanStepParams = __Infer<typeof RemindPlanStepReducer>;
export type ReviewCareParams = __Infer<typeof ReviewCareReducer>;
export type RevokeMemberParams = __Infer<typeof RevokeMemberReducer>;
export type SaveTripParams = __Infer<typeof SaveTripReducer>;
export type SendMessageParams = __Infer<typeof SendMessageReducer>;
export type SetAutoCareParams = __Infer<typeof SetAutoCareReducer>;
export type SetSharingPreferenceParams = __Infer<typeof SetSharingPreferenceReducer>;
export type ShareCareBriefParams = __Infer<typeof ShareCareBriefReducer>;
export type ShareLatestSummaryParams = __Infer<typeof ShareLatestSummaryReducer>;
export type SharePlanStepParams = __Infer<typeof SharePlanStepReducer>;
export type SharePreparedVisitParams = __Infer<typeof SharePreparedVisitReducer>;
export type ShareSummaryParams = __Infer<typeof ShareSummaryReducer>;
export type UnpublishEmergencyCardParams = __Infer<typeof UnpublishEmergencyCardReducer>;
export type UpdatePlanParams = __Infer<typeof UpdatePlanReducer>;
export type UpdateReminderParams = __Infer<typeof UpdateReminderReducer>;

