import {TripForm} from './CarePlan'
import {useState} from 'react'
import type {Snapshot} from './session'
import type {DbConnection} from './module_bindings'
import {useDeviceDraft,tokenKey} from './device'
const slots=['2026-10-14T20:00:00Z','2026-10-15T15:00:00Z','2026-10-16T18:00:00Z']
function localInput(date:Date){return new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,16)}
const display=(iso:string)=>new Date(iso).toLocaleString('en-US',{timeZone:'America/Chicago',dateStyle:'medium',timeStyle:'short'})+' CT'
type Props={session:Snapshot&{connection:DbConnection|null};mutate:(action:()=>Promise<void>)=>Promise<boolean>;busy:boolean}
export function SandboxConnect({session,mutate,busy}:Props){
 const [scenario,setScenario]=useState(session.sandboxLink?.scenario??(session.me?.name==='Daniel'?'polypharmacy-senior':'baseline-adult'))
 const [requestId,setRequestId]=useDeviceDraft(session.me!.identity,'sandboxRequest','')
 async function run(event?:string){let id=requestId;if(!id){id=crypto.randomUUID();setRequestId(id)}await mutate(async()=>{const res=await fetch('/api/sandbox/connect',{method:'POST',headers:{Authorization:`Bearer ${sessionStorage.getItem(tokenKey)??''}`,'Content-Type':'application/json'},body:JSON.stringify({requestId:id,scenario:session.sandboxLink?.scenario??scenario,event})});if(!res.ok)throw Error('Sandbox connection did not finish. Check status and retry.');})}
 return <section className="record-connect"><strong>Connect FinchNode sandbox</strong><p>Fictional records through your account. The key stays on the server.</p><label htmlFor="sandbox-scenario">Patient scenario</label><select id="sandbox-scenario" value={session.sandboxLink?.scenario??scenario} disabled={!!session.sandboxLink} onChange={e=>setScenario(e.target.value)}>{['polypharmacy-senior','baseline-adult','sparse-record','consent-partial','multi-source-overlap'].map(s=><option key={s}>{s}</option>)}</select><button className="primary" disabled={busy} onClick={()=>void run()}>{session.sandboxLink?'Refresh sandbox records':'Connect fictional patient'}</button>{session.sandboxLink&&<><p role="status">Sandbox: {session.sandboxLink.status}</p>{session.sandboxLink.status==='waiting'&&<p>FinchNode is still syncing. Refresh resumes the same patient; no demo data is substituted.</p>}<details><summary>Sandbox test controls</summary><p>These change only this fictional patient's source. Revocation stops future record access.</p><button className="secondary" disabled={busy||!session.sandboxLink.subject} onClick={()=>void run('records.advance')}>Simulate record update</button><button className="secondary" disabled={busy||!session.sandboxLink.subject} onClick={()=>{if(window.confirm('Revoke this fictional sandbox connection? Its imported private records will be cleared.'))void run('consent.revoke')}}>Revoke sandbox consent</button></details></>}</section>
}
export function CareActions({session,mutate,busy}:Props){
 const [open,setOpen]=useState<'reminder'|'booking'|null>(null)
 const [title,setTitle]=useDeviceDraft(session.me!.identity,'reminderTitle','Prepare for my appointment')
 const [time,setTime]=useDeviceDraft(session.me!.identity,'reminderTime','')
 const [slot,setSlot]=useDeviceDraft(session.me!.identity,'bookingSlot',slots[0])
 const [reminderId,setReminderId]=useDeviceDraft(session.me!.identity,'reminderRequest','')
 const [bookingId,setBookingId]=useDeviceDraft(session.me!.identity,'bookingRequest','')
 async function saveReminder(){const date=Date.parse(time);if(!Number.isFinite(date))return;const id=reminderId||crypto.randomUUID();setReminderId(id);if(await mutate(()=>session.connection!.reducers.createReminder({requestId:id,title,dueAt:BigInt(date)*1000n}))){setReminderId('');setOpen(null)}}
 async function confirm(){const id=bookingId||crypto.randomUUID();setBookingId(id);if(await mutate(()=>session.connection!.reducers.confirmDemoBooking({requestId:id,slot}))){setBookingId('');setOpen(null)}}
 return <section className="record-connect" aria-label="Your reminders and visits"><div>{session.reminders.filter(r=>r.status==='due').map(r=><div key={r.id} role="alert"><strong>Reminder: {r.title}</strong><p>Due {display(new Date(Number(r.dueAt/1000n)).toISOString())}</p><button className="secondary" onClick={()=>void mutate(()=>session.connection!.reducers.updateReminder({id:r.id,action:'dismiss'}))}>{r.id.startsWith('auto-care:')?'Checked in':'Dismiss reminder'}</button>{r.id.startsWith('auto-care:')&&<button className="secondary" onClick={()=>void mutate(()=>session.connection!.reducers.updateReminder({id:r.id,action:'cancel'}))}>Stop this check-in</button>}</div>)}</div><button className="secondary" onClick={()=>setOpen(open==='reminder'?null:'reminder')}>Add reminder</button> <button className="secondary" onClick={()=>setOpen(open==='booking'?null:'booking')}>Plan a demo visit</button>
 <TripForm session={session} mutate={mutate} busy={busy}/>
 {open==='reminder'&&<div><h3>Review your reminder</h3><p>Only you. Appears in Kin while open, or when you return. No email, SMS or closed-app notification.</p><label htmlFor="reminder-title">Reminder</label><input id="reminder-title" value={title} maxLength={200} onChange={e=>{setReminderId('');setTitle(e.target.value)}}/><label htmlFor="reminder-time">When · your device's local time</label><input id="reminder-time" type="datetime-local" value={time} onChange={e=>{setReminderId('');setTime(e.target.value)}}/>{time&&Number.isFinite(Date.parse(time))&&<p>Review: {title} · {display(new Date(time).toISOString())}</p>}<button className="primary" disabled={busy||!title.trim()||!time} onClick={()=>void saveReminder()}>Save in-app reminder</button><button className="secondary" onClick={()=>setOpen(null)}>Cancel</button></div>}
 {open==='booking'&&<div><h3>Choose a fictional appointment</h3><p>Demo Community Clinic · Primary care. Synthetic slots only. No real provider is contacted.</p><label htmlFor="visit-slot">Demo availability</label><select id="visit-slot" value={slot} onChange={e=>{setBookingId('');setSlot(e.target.value)}}>{slots.map(s=><option key={s} value={s}>{display(s)}</option>)}</select><p>Review: Demo Community Clinic · Primary care · {display(slot)}. Private until you approve sharing.</p><button className="primary" disabled={busy} onClick={()=>void confirm()}>Confirm synthetic booking</button><button className="secondary" onClick={()=>setOpen(null)}>Cancel</button></div>}
 <details><summary>Your saved reminders and visits</summary>{session.reminders.filter(r=>r.status!=='due').map(r=><div key={r.id}><strong>{r.title}</strong><p>{display(new Date(Number(r.dueAt/1000n)).toISOString())} · {r.status}</p>{r.status==='scheduled'&&<button className="secondary" onClick={()=>void mutate(()=>session.connection!.reducers.updateReminder({id:r.id,action:'cancel'}))}>Cancel reminder</button>}</div>)}{session.bookings.map(b=><div key={b.id}><strong>Demo Community Clinic</strong><p>{display(b.slot)} · {b.status==='confirmed-demo'?'Confirmed synthetic booking':'Cancelled'}</p>{b.status!=='cancelled'&&<><button className="secondary" onClick={()=>{setReminderId('');setTitle('Prepare for my demo visit');setTime(localInput(new Date(Date.parse(b.slot)-7200000)));setOpen('reminder')}}>Add visit reminder</button><button className="secondary" onClick={()=>void mutate(()=>session.connection!.reducers.cancelDemoBooking({id:b.id}))}>Cancel synthetic booking</button><p>Cancellation does not cancel separately saved reminders.</p></>}</div>)}{!session.reminders.length&&!session.bookings.length&&<p>Nothing saved yet.</p>}</details></section>
}
