import {useState} from 'react'
import type {Snapshot} from './session'
import type {DbConnection} from './module_bindings'
import {useDeviceDraft} from './device'
const slots=['2026-10-18T15:00:00Z','2026-10-19T15:00:00Z','2026-10-20T15:00:00Z']
const fields={bloodType:'Blood type',allergies:'Allergies and reactions',medications:'Medication information',conditions:'Important conditions',contact:'Emergency contact',notes:'Other important information'}
const blank={bloodType:'Unknown',allergies:'',medications:'',conditions:'',contact:'',notes:''}
type Card=typeof blank
const time=(iso:string)=>new Date(iso).toLocaleString('en-US',{timeZone:'America/Chicago',dateStyle:'medium',timeStyle:'short'})+' CT'
export function FamilyCare({session,mutate,busy}:{session:Snapshot&{connection:DbConnection|null};mutate:(fn:()=>Promise<void>)=>Promise<boolean>;busy:boolean}){
 const [now]=useState(()=>Date.now()),[copyNotice,setCopyNotice]=useState(''),[open,setOpen]=useState(''),[booking,setBooking]=useState(false),[editing,setEditing]=useState(false),[patient,setPatient]=useDeviceDraft(session.me!.identity,'familyBookingPatient',session.me!.identity),[slot,setSlot]=useDeviceDraft(session.me!.identity,'familyBookingSlot',slots[0]),[request,setRequest]=useDeviceDraft(session.me!.identity,'familyBookingRequest','')
 const own=(session.emergencyCards??[]).find(c=>c.owner===session.me!.identity)
 const [draft,setDraft]=useDeviceDraft(session.me!.identity,'emergencyCardDraft',own?.data??JSON.stringify(blank))
 let data:Card;try{data={...blank,...JSON.parse(draft)}}catch{data=blank}
 const visits=session.familyVisits??[]
 function edit(){setEditing(true);setOpen(session.me!.identity)}
 return <section className="family-care" aria-label="Family care"><div className="family-care-bar"><div className="family-profile-list">{session.members.map(m=><button className="secondary" key={m.identity} onClick={()=>setOpen(open===m.identity?'':m.identity)} aria-expanded={open===m.identity}>{m.name}<small>Emergency card</small></button>)}</div><button className="secondary" onClick={()=>setBooking(!booking)}>Arrange a visit</button></div>
 {open&&(()=>{const member=session.members.find(m=>m.identity===open),card=(session.emergencyCards??[]).find(c=>c.owner===open);if(!member)return null;const info:Card=card?JSON.parse(card.data):blank;return <div className="family-emergency-card"><h3>{member.name}’s emergency card</h3>{card?<><small>Shared with this family · Reviewed {time(new Date(Number(card.reviewedAt/1000n)).toISOString())}</small><dl>{Object.entries(fields).map(([key,label])=><div key={key}><dt>{label}</dt><dd>{info[key as keyof Card]||'Not provided'}</dd></div>)}</dl><p>Reviewed by {member.name}. Self-reported information; clinical staff must verify it. Medication entries do not confirm current use.</p></>:<p>{member.name} hasn’t shared an emergency card. Their private records remain private.</p>}{open===session.me!.identity&&!editing&&<button className="secondary" onClick={edit}>{card?'Edit my card':'Create my card'}</button>}{open===session.me!.identity&&card&&!editing&&<button className="secondary" disabled={busy} onClick={()=>void mutate(()=>session.connection!.reducers.unpublishEmergencyCard({}))}>Remove shared card</button>}{open===session.me!.identity&&editing&&<div className="family-card-editor"><p>Review the exact information below before sharing with {session.members.filter(m=>m.identity!==session.me!.identity).map(m=>m.name).join(', ')||'future family members'}. New family members can see the current card.</p><button className="secondary" onClick={()=>{const copied={...data,allergies:session.records.filter(r=>r.category==='Allergies').map(r=>r.text).join('\n'),medications:session.records.filter(r=>r.category==='Medications').map(r=>r.text).join('\n'),conditions:session.records.filter(r=>r.category==='Conditions').map(r=>r.text).join('\n')};if(Object.values(copied).some(v=>v.length>800)){setCopyNotice('These records exceed the card limit. Select and enter the essential information below; nothing was cut off.');return}setCopyNotice('');setDraft(JSON.stringify(copied))}}>Copy from my records</button>{copyNotice&&<p role="status">{copyNotice}</p>}<small>Copied text is editable and is not verified. Blank fields mean unknown, not none.</small>{Object.entries(fields).map(([key,label])=><label key={key}>{label}{key==='bloodType'?<select value={data.bloodType} onChange={e=>setDraft(JSON.stringify({...data,bloodType:e.target.value}))}>{['Unknown','A+','A-','B+','B-','AB+','AB-','O+','O-'].map(t=><option key={t}>{t}</option>)}</select>:<textarea value={data[key as keyof Card]} maxLength={800} onChange={e=>setDraft(JSON.stringify({...data,[key]:e.target.value}))}/>}</label>)}<button className="primary" disabled={busy} onClick={()=>void(async()=>{if(await mutate(()=>session.connection!.reducers.publishEmergencyCard({data:JSON.stringify(data)})))setEditing(false)})()}>Share reviewed card with family</button><button className="secondary" onClick={()=>setEditing(false)}>Cancel</button></div>}</div>})()}
 {booking&&<div className="family-visit-form"><h3>Arrange a family visit</h3><p>Sandbox booking · Fictional clinic and slots. No real provider is contacted. Visit details are shared with this family.</p><label>Who is the visit for?<select value={patient} onChange={e=>{setPatient(e.target.value);setRequest('')}}>{session.members.map(m=><option key={m.identity} value={m.identity}>{m.name}</option>)}</select></label><label>Demo Community Clinic · Primary care<select value={slot} onChange={e=>{setSlot(e.target.value);setRequest('')}}>{slots.map(s=><option key={s} value={s} disabled={Date.parse(s)<=now||visits.some(v=>v.slot===s&&v.status==='confirmed-demo')}>{time(s)}</option>)}</select></label><p>Review: {session.members.find(m=>m.identity===patient)?.name} · {time(slot)} · Synthetic reservation</p><button className="primary" disabled={busy||Date.parse(slot)<=now||visits.some(v=>v.slot===slot&&v.status==='confirmed-demo')} onClick={()=>void(async()=>{const id=request||crypto.randomUUID();setRequest(id);if(await mutate(()=>session.connection!.reducers.confirmFamilyVisit({requestId:id,patient,slot}))){setRequest('');setBooking(false)}})()}>Confirm sandbox visit</button><button className="secondary" onClick={()=>setBooking(false)}>Cancel</button></div>}
 {!!visits.length&&<details><summary>Family visits · {visits.filter(v=>v.status==='confirmed-demo'&&Date.parse(v.slot)>now).length} upcoming</summary>{visits.map(v=><div key={v.id}><strong>{v.patientName} · {time(v.slot)}</strong><p>{v.status==='cancelled'?'Cancelled':'Synthetic reservation'} · Arranged by {v.organizerName}</p>{v.status!=='cancelled'&&[v.organizer,v.patient].includes(session.me!.identity)&&<button className="secondary" disabled={busy} onClick={()=>void mutate(()=>session.connection!.reducers.cancelFamilyVisit({id:v.id}))}>Cancel sandbox visit</button>}</div>)}</details>}
 </section>
}
